### ISSUE TITLE
[Feature Request] `PR_SET_SPECULATION_CTRL`/`PR_GET_SPECULATION_CTRL`

### ISSUE THREAD

**Issue by rusty-snake** [cptpcrd/capctl#1]
I would welcome an interface for the `PR_SET_SPECULATION_CTRL` and `PR_GET_SPECULATION_CTRL` prctls.

**Comment by rusty-snake** [comment]
Do you have a plan for a new release?

**Comment by cptpcrd** [comment]
Released:
https://github.com/cptpcrd/capctl/releases/tag/v0.2.2
https://crates.io/crates/capctl/0.2.2
